import Image from "next/image";
import type { Metadata } from "next";
import Link from 'next/link'

import Button from '@/components/Button'
import Icon from '@/components/Icon'
import PortfolioCard from '@/components/PortfolioCard'

import TECHSTACK from '@/assets/stack.json'
import WEBSITES from '@/assets/websites.json'
import APPS from '@/assets/apps.json'

export const metadata: Metadata = {
  title: "Kyra's Portfolio",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex flex-col gap-20 px-[5vw] py-[15vh] ">
      <header className='flex flex-col gap-5 md:mx-[10vw]'>
        <h1 className='tracking-tighter'>Hi! I'm Kyra Ezikeuzor, a student and developer.</h1>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor turpis libero, sit amet molestie massa ultrices ac. Mauris non gravida leo, vel blandit ipsum. Pellentesque pretium ullamcorper bibendum. 
        </p>
        <div className='flex flex-row gap-3 items-center'>
          <Button>About</Button>
          <Link href='/hire-me' className='font-medium'>Hire Me ➝</Link>
        </div>
      </header>
      <section className="flex flex-col md:flex-row justify-between gap-2 md:mx-[10vw]">
        <div className='w-full md:w-3/5 flex flex-col gap-5'>
          <h2>A Bit About Me. </h2>
          <ul className='w-full flex flex-col gap-1'>
            <li className='w-full flex flex-row gap-5'>
              <span>•</span>
              <p>
                Ever since I was a kid, I have always been fascinated with how diverse the web was -- and that passion has led me to pursue web development.Ever since I was a kid, I have always been fascinated with how diverse the web was -- and that passion has led me to pursue web development.
              </p>
            </li>
            <li className='flex flex-row gap-5'>
              <span>•</span>
              <p>
                Ever since I was a kid, I have always been fascinated with how diverse the web was -- and that passion has led me to pursue web development.Ever since I was a kid, I have always been fascinated with how diverse the web was -- and that passion has led me to pursue web development.
              </p>
            </li>
            <li className='flex flex-row gap-5'>
              <span>•</span>
              <p>
                Ever since I was a kid, I have always been fascinated with how diverse the web was -- and that passion has led me to pursue web development.Ever since I was a kid, I have always been fascinated with how diverse the web was -- and that passion has led me to pursue web development.
              </p>
            </li>
          </ul>
        </div>
        <div className='w-full md:w-2/5'>
          <img className='w-full h-auto' src='https://chetachilabs.com/img/profile-img.png'/>
        </div>
      </section>
      <section className='flex flex-col gap-5 md:mx-[10vw]'>
        <h2 className='tracking-tighter'>Tech Stack & Skills</h2>
        <div className='flex flex-row flex-wrap gap-2'>
          {TECHSTACK.map((item,index)=>(
            <div className='flex flex-col gap-2 items-center rounded-2xl border border-[--clr-base-accent] px-4 py-4'>
              <img src={item.src} className='w-auto h-16'/>
              <div className='font-medium'>
                {item.name}
              </div>
            </div>
          ))}
        </div>

      </section>
      <section className='flex flex-col gap-5 md:mx-[10vw]'>
        <span>
          <h2 className='tracking-tighter'>My Portfolio</h2>
          <div>
            See A
          </div>
        </span>
        
        
        <div className='flex flex-col gap-2'>
            {/*<h3 className='tracking-tighter'>Apps</h3>*/}
            <div className='flex flex-col md:grid md:grid-cols-2 lg:grid-cols-3 gap-2'>
              {APPS.map((item,index)=>(
                <PortfolioCard
                name={item.name}
                description={item.description}
                src={item.src}
                url={item.url}
                stack={item.stack}/>
              ))}
            </div>
        </div>

        <div className='flex flex-col gap-2'>
            {/*<h3 className='tracking-tighter'>Websites</h3>*/}
            <div className='flex flex-col md:grid md:grid-cols-2 lg:grid-cols-4 gap-2'>
              {WEBSITES.map((item,index)=>(
                <div className='flex flex-col gap-4 rounded-lg border border-[--clr-base-accent] shadow-sm px-2 py-2'>
                  <img src={item.src} className='w-full h-auto rounded-md shadow-sm border border-[--clr-base-accent]'/>

                  <div className='flex flex-col gap-2 px-3 py-2'>
                    <h4>{item.name}</h4>
                    <p className='text-sm md:text-sm'>
                      {item.description}
                    </p>
                    <div className='flex flex-row gap-1 flex-wrap items-center'>
                      {item.stack.map((tag,index)=>(
                        <span className='bg-[--clr-grey-light] border border-[--clr-base-accent] rounded-xl px-2 text-sm'>
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
              </div>
              ))}
            </div>

        </div>
        

      </section>

    </main>
  );
}
